# Generated by Django 4.0.4 on 2022-04-28 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_alter_clube_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='Cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controle.cidade'),
        ),
    ]
